import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar1 from "@/compaonents/Navbar1";
import Navbar2 from "@/compaonents/Navbar2";
import ImageA from "@/compaonents/images";
import BuyerNavbar from "@/compaonents/BuyerNavbar";
import SellerNavbar from "@/compaonents/SellerNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <Navbar1 />
        <Navbar2 />
        <ImageA />
        <BuyerNavbar />
        <SellerNavbar />

        {children}
      </body>
    </html>
  );
}
